### ISSUE TITLE
.Unitypackage

### ISSUE THREAD

**Issue by MertcanBayraktar** [Renge-Games/UnityAssetRetriever#2]
Can I modify this package so that it downloads them as unitypackages and does not import directly into that project?

**Comment by Sam-Schiffer** [comment]
Why would you want to do that? Just curious.

**Comment by MertcanBayraktar** [comment]
I have a hundreds of assets in my assets list, i would like to move them to my google disk by downloading them in bulk.That was my main reason

**Comment by Sam-Schiffer** [comment]
I wouldn't know how to do that off the top of my head, but sure, you can do that.

**Comment by MertcanBayraktar** [comment]
After i issued a topic here i researched some and found that if you click download button in package manager and dont click import after. .Unitypackage file gets saved in the C:\Users\[WindowsName]\AppData\Roaming\Unity\Asset Store-5.x folder.So my tought that easiest way to turn this script is that I'll remove import function in the code but only use the download functionalities then search by .Unitypackage in that directory path and get the all unitypackages which are downloaded

**Comment by Sam-Schiffer** [comment]
Ah yes, of course. The asset cache directory. I might add an option to only download and not import the selected assets.
